# Generated by Django 5.2 on 2025-04-28 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text="Âge de l'utilisateur", null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='can_be_contacted',
            field=models.BooleanField(default=False, help_text="L'utilisateur accepte d'être contacté."),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='can_data_be_shared',
            field=models.BooleanField(default=False, help_text="L'utilisateur accepte que ses données soient partagées."),
        ),
    ]
