# Generated by Django 5.2.1 on 2025-05-09 18:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique du commentaire', primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='Texte du commentaire')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='Date et heure de création du commentaire')),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text="Date et heure d'ajout du contributeur")),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Titre de l'issue", max_length=128)),
                ('description', models.TextField(help_text="Description détaillée de l'issue")),
                ('tag', models.CharField(choices=[('Bug', 'Bug'), ('Feature', 'Feature'), ('Task', 'Task')], help_text="Étiquette de l'issue", max_length=10)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], help_text='Niveau de priorité', max_length=10)),
                ('status', models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Finished', 'Finished')], default='To Do', help_text="Statut actuel de l'issue", max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'issue")),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre du projet', max_length=128)),
                ('description', models.TextField(help_text='Description détaillée du projet')),
                ('type', models.CharField(choices=[('Back-End', 'Back-End'), ('Front-End', 'Front-End'), ('iOS', 'iOS'), ('Android', 'Android')], help_text='Type ou catégorie du projet', max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='Date et heure de création du projet')),
            ],
        ),
    ]
