# Generated by Django 5.2.1 on 2025-05-09 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(help_text='Utilisateur auteur du commentaire', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contributor',
            name='user',
            field=models.ForeignKey(help_text='Utilisateur contributeur', on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='assignee_user',
            field=models.ForeignKey(blank=True, help_text="Utilisateur assigné pour traiter l'issue (optionnel)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='author',
            field=models.ForeignKey(help_text="Utilisateur ayant créé l'issue", on_delete=django.db.models.deletion.CASCADE, related_name='issues_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(help_text='Issue à laquelle le commentaire est lié', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.issue'),
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(help_text='Utilisateur créateur du projet', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(help_text="Projet auquel l'issue appartient", on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.project'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='project',
            field=models.ForeignKey(help_text='Projet associé au contributeur', on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together={('user', 'project')},
        ),
    ]
